[package]
name = "Soluna"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.28.1"
geolocation = "0.2.1"
ratatui = "0.28.1"
reqwest = "0.12.7"
serde_json = "1.0.128"
tokio = { version = "1", features = ["full"] }
