pub fn country_emote(country: String) -> String {
    let country = country.replace("\"", "");
    
    match country.as_str() {
        "United States" => "🇺🇸".to_string(),
        "United Kingdom" => "🇬🇧".to_string(),
        "Canada" => "🇨🇦".to_string(),
        "Australia" => "🇦🇺".to_string(),
        "Germany" => "🇩🇪".to_string(),
        "France" => "🇫🇷".to_string(),
        "Italy" => "🇮🇹".to_string(),
        "Spain" => "🇪🇸".to_string(),
        "Netherlands" => "🇳🇱".to_string(),
        "Brazil" => "🇧🇷".to_string(),
        "Japan" => "🇯🇵".to_string(),
        "China" => "🇨🇳".to_string(),
        "South Korea" => "🇰🇷".to_string(),
        "India" => "🇮🇳".to_string(),
        "Russia" => "🇷🇺".to_string(),
        "Mexico" => "🇲🇽".to_string(),
        "South Africa" => "🇿🇦".to_string(),
        "Argentina" => "🇦🇷".to_string(),
        "Sweden" => "🇸🇪".to_string(),
        "Norway" => "🇳🇴".to_string(),
        "Switzerland" => "🇨🇭".to_string(),
        "Belgium" => "🇧🇪".to_string(),
        "Austria" => "🇦🇹".to_string(),
        "Denmark" => "🇩🇰".to_string(),
        "Finland" => "🇫🇮".to_string(),
        "Ireland" => "🇮🇪".to_string(),
        "New Zealand" => "🇳🇿".to_string(),
        "Portugal" => "🇵🇹".to_string(),
        "Greece" => "🇬🇷".to_string(),
        "Turkey" => "🇹🇷".to_string(),
        "Saudi Arabia" => "🇸🇦".to_string(),
        "Israel" => "🇮🇱".to_string(),
        "Egypt" => "🇪🇬".to_string(),
        "Nigeria" => "🇳🇬".to_string(),
        "Kenya" => "🇰🇪".to_string(),
        "Indonesia" => "🇮🇩".to_string(),
        "Thailand" => "🇹🇭".to_string(),
        "Vietnam" => "🇻🇳".to_string(),
        "Philippines" => "🇵🇭".to_string(),
        "Malaysia" => "🇲🇾".to_string(),
        "Singapore" => "🇸🇬".to_string(),
        "Pakistan" => "🇵🇰".to_string(),
        "Bangladesh" => "🇧🇩".to_string(),
        "Ukraine" => "🇺🇦".to_string(),
        "Poland" => "🇵🇱".to_string(),
        "Czech Republic" => "🇨🇿".to_string(),
        "Hungary" => "🇭🇺".to_string(),
        "Romania" => "🇷🇴".to_string(),
        "Chile" => "🇨🇱".to_string(),
        "Colombia" => "🇨🇴".to_string(),
        "Peru" => "🇵🇪".to_string(),
        _ => "🏳️".to_string()
    }
}